#!/bin/sh

# No hacer nada si no estamos configurando bond0
[ "$IFACE" != 'bond0' ] && exit 0

. /etc/network/if-pre-up.d/puente

# La lista de puertos TCP donde la Pine ofrece servicios
# visibles a Internet.
# Valor actual: ninguno
readonly PUERTOS_TCP_PUBLICOS=''
# La lista de puertos UDP donde la Pine ofrece servicios
# visibles a Internet.
# Valor actual: NTP
readonly PUERTOS_UDP_PUBLICOS='123'

################
# ENRUTAMIENTO #
################

# La Pine no es un enrutador, excepto para
# las redes que se especifiquen manualmente
iptables -P FORWARD DROP || exit $?

# Enrutar paquetes desde VLANs hacia Internet (máscara /16 por posibilidad de tethering)
iptables -A FORWARD -s 172.16.0.0/12 -o bond0 ! -d 192.168.0.0/16 -j ACCEPT || exit $?

# Enrutar paquetes desde Internet hacia VLANs
iptables -A FORWARD -i bond0 ! -s 192.168.0.0/16 -d 172.16.0.0/12 -j ACCEPT || exit $?

# Activar enrutamiento IPv4
echo 1 > /proc/sys/net/ipv4/ip_forward

########
# SNAT #
########

# Los paquetes enrutados desde las VLAN por bond0 sufren
# SNAT, para que la pasarela del ISP pueda abstraerse de la
# presencia de los contenedores
iptables -t nat -A POSTROUTING ! -s 192.168.0.0/27 -o bond0 -j SNAT --to-source 192.168.0.29 || exit $?

###############
# CORTAFUEGOS #
###############

# Descartar sin respuesta paquetes entrantes que no autoricemos explícitamente
iptables -P INPUT DROP || exit $?

# Siempre aceptar paquetes provenientes de la LAN física, si van destinados
# a la interfaz situada en la LAN física de la Pine
iptables -A INPUT -s 192.168.0.0/16 -d 192.168.0.29 -j ACCEPT || exit $?
iptables -A INPUT -s 192.168.0.0/16 -d 192.168.0.31 -j ACCEPT || exit $?

# Aceptar paquetes destinados a la misma VLAN por la que vienen
# (aislamiento entre servicios ofrecidos por la Pine para diferentes VLAN)
for vlan in $(seq 1 $NUM_VLAN); do
	iptables -A INPUT -s $(vlanARed $vlan).0/24 -d $(vlanARed $vlan).0/24 -j ACCEPT || exit $?
	iptables -A INPUT -i br0.$vlan -d $(vlanARed $vlan).255 -j ACCEPT || exit $?
done

# Aceptar broadcasts limitados, vengan de donde vengan.
# Se asume que un paquete proveniente de Internet no tiene
# nunca como destino un broadcast limitado
iptables -A INPUT -d 255.255.255.255 -j ACCEPT || exit $?

# Exponer servicios brindados a la LAN física que se desea que sean accesibles desde Internet.
# Nunca se exponen servicios brindados exclusivamente a las VLAN
for puerto in $PUERTOS_TCP_PUBLICOS; do
	if [ -n "$puerto" ]; then
		iptables -A INPUT -i bond0 -d 192.168.0.29 -p tcp --dport $puerto -j ACCEPT || exit $?
	fi
done
for puerto in $PUERTOS_UDP_PUBLICOS; do
	if [ -n "$puerto" ]; then
		iptables -A INPUT -i bond0 -d 192.168.0.29 -p udp --dport $puerto -j ACCEPT || exit $?
	fi
done

# Aceptar paquetes que sean una respuesta a paquetes enviados
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT || exit $?

##############
# TABLAS ARP #
##############

# Añadir MAC de puerta de enlace de LAN física a tabla ARP, para
# inmunizarnos contra ARP spoofing y reducir tráfico
ip neigh replace 192.168.0.1 lladdr '08:80:39:e0:16:5f' nud permanent dev bond0
