#!/bin/sh

# Waits until a ICMP ECHO request has been successfully sent to the
# defaulta gateway, in order to wait until the PHY has setup the link,
# and configures static ARP entries, to protect us against ARP spoofing
# and reduce network overhead a little bit.
initialize() {
	printf '%s: Waiting for Ethernet PHY to initialize link' "$0"

	# Try to ping the gateway until it responds
	tick=1
	while ! ping -c 1 -q -W 0.25 192.168.0.1 >/dev/null 2>&1; do
		if [ "$((tick % 8))" -eq 0 ]; then
			printf '.'
		fi

		tick=$((tick + 1))
	done

	printf '\n'

	echo "$0: adding static ARP entries for $IFACE"
	ip neigh add 192.168.0.1 lladdr 08:80:39:e0:16:5f nud permanent dev "$IFACE"
}

if [ "$IFACE" = 'eth0' ]; then
	case "$PHASE" in
		post-up) initialize;;
	esac
fi
