#!/bin/sh

# Waits until a ICMP ECHO request has been successfully sent to the
# default gateway, in order to wait until the PHY has setup the link,
# and configures static ARP entries, to protect us against ARP spoofing
# later on and reduce network overhead a little bit.
initialize() {
	printf '%s: waiting for the Ethernet PHY to initialize link' "$0"

	# Try to ping the gateway until it responds
	tick=1
	while ! ping -c 1 -q -W 0.25 192.168.0.1 >/dev/null 2>&1; do
		if [ "$((tick % 4))" -eq 0 ]; then
			printf '.'
		fi

		if [ $tick -ge 144 ]; then
			printf "\n%s: we have been waiting for the PHY to initialize for 36 seconds, which is too much. Bailing\n" "$0" >&2
			return 1
		fi

		tick=$((tick + 1))
	done

	printf '\n'

	echo "$0: making gateway ARP entry static for $IFACE"
	ip neigh replace 192.168.0.1 nud permanent dev "$IFACE"
}

if [ "$IFACE" = 'eth0' ]; then
	case "$PHASE" in
		post-up) initialize;;
	esac
fi
