#!/bin/sh

# Parar el proceso wpa_supplicant encargado de mantener
# la autenticación de capa de enlace con el AP asociado
# a la interfaz
case $IFACE in
	wlan*)
		# Matar procesos wpa_supplicant que estén asociados con esta interfaz
		ps -C wpa_supplicant -o cmd= -o pid= | awk "/-i$IFACE/{ match(\$0, /[0-9]+$/, pid); print \"kill\", pid[0] | \"/bin/sh\" } END { close(\"/bin/sh\") }";;
	--all)
		killall -q wpa_supplicant
		# Ignorar estado de error devuelto por killall:
		# no es crítico que no se estuviese ejecutando wpa_supplicant
		exit 0;;
esac
